[Interface]
PrivateKey = GMtd/AiU2IilcpG+OXYEJcnDoGOSq3zzeHporRMHvX8=
Address = 10.10.0.2/24

[Peer]
PublicKey = xgx+hojIqrK4dENlNBzomgvm+WTad+am0K0+D1frr3U=
Endpoint = 34.100.200.152:51820
AllowedIPs = 10.10.0.0/24
PersistentKeepalive = 25
